/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as PanelQaRouteImport } from './routes/panel-qa'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as StartRouteImport } from './routes/start'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as IdeaIdeaIdRouteImport } from './routes/idea.$ideaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelQaRoute = PanelQaRouteImport.update({
  id: '/panel-qa',
  path: '/panel-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdRoute = IdeaIdeaIdRouteImport.update({
  id: '/idea/$ideaId',
  path: '/idea/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/judge': typeof JudgeRoute
  '/panel-qa': typeof PanelQaRoute
  '/results': typeof ResultsRoute
  '/start': typeof StartRoute
  '/tracker': typeof TrackerRoute
  '/idea/$ideaId': typeof IdeaIdeaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/judge': typeof JudgeRoute
  '/panel-qa': typeof PanelQaRoute
  '/results': typeof ResultsRoute
  '/start': typeof StartRoute
  '/tracker': typeof TrackerRoute
  '/idea/$ideaId': typeof IdeaIdeaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/judge': typeof JudgeRoute
  '/panel-qa': typeof PanelQaRoute
  '/results': typeof ResultsRoute
  '/start': typeof StartRoute
  '/tracker': typeof TrackerRoute
  '/idea/$ideaId': typeof IdeaIdeaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/judge'
    | '/panel-qa'
    | '/results'
    | '/start'
    | '/tracker'
    | '/idea/$ideaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/judge'
    | '/panel-qa'
    | '/results'
    | '/start'
    | '/tracker'
    | '/idea/$ideaId'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/judge'
    | '/panel-qa'
    | '/results'
    | '/start'
    | '/tracker'
    | '/idea/$ideaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  JudgeRoute: typeof JudgeRoute
  PanelQaRoute: typeof PanelQaRoute
  ResultsRoute: typeof ResultsRoute
  StartRoute: typeof StartRoute
  TrackerRoute: typeof TrackerRoute
  IdeaIdeaIdRoute: typeof IdeaIdeaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-qa': {
      id: '/panel-qa'
      path: '/panel-qa'
      fullPath: '/panel-qa'
      preLoaderRoute: typeof PanelQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId': {
      id: '/idea/$ideaId'
      path: '/idea/$ideaId'
      fullPath: '/idea/$ideaId'
      preLoaderRoute: typeof IdeaIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  JudgeRoute: JudgeRoute,
  PanelQaRoute: PanelQaRoute,
  ResultsRoute: ResultsRoute,
  StartRoute: StartRoute,
  TrackerRoute: TrackerRoute,
  IdeaIdeaIdRoute: IdeaIdeaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
